hello:
	gcc -Wall -ansi -pedantic-errors hello.c -o hello
Hello:
	gcc -Wall -ansi -pedantic-errors Hello.c -o Hello
print:
	gcc -Wall -ansi -pedantic-errors print.c -o print
scan:
	gcc -Wall -ansi -pedantic-errors scan.c -o scan

clean:
	rm -f hello print Hello
